title: An Inky Page...
tagline: Not actually ink, but definitely a page of some kind.
# theme: jekyll-theme-slate
google_analytics: UA-3178374-2
permalink: /:year/:month/:title/
author:
  name: Andrew Jorgensen
  email: andrew@jorgensenfamily.us
  github: ajorg
  twitter: ajorg
